spring:
  datasource:
  generate-unique-name: false
  name: tacocloud
  h2:
    console:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: YOUR_APP_ID
            clientSecret: YOUR_APP_SECRET
            scope:
              - email
              - public_profile

#spring:
#  data:
#  cassandra:
#  keyspace-name: taco_cloud
#  schema-action: recreate
#  local-datacenter: datacenter1