spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: false

  data:
    rest:
      base-path: /data-api

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

#  jms:
#      template:
#        default-destination: tacocloud.order.queue

#  rabbitmq:
#    template:
#      exchange: tacocloud.order
#      routing-key: kitchens.central

  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: TestTopic
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer